log:
  exp_name: spiderman
  save_interval: 18
guide:
  text: "spiderman, {} view"
  diffusion_name: stabilityai/stable-diffusion-2-depth
  shape_scale: 0.6
  append_direction: True
  shape_path: shapes/human.obj
  texture_resolution: 1024
  guidance_scale: 10
  texture_interpolation_mode: 'bilinear'
optim:
  seed: 2
render:
  front_offset: 0
  overhead_range: 0