log:
  exp_name: spiderman_kaws
guide:
  text: "A toy of Spiderman, {} view"
  text_front: "A toy of Spiderman, front view"
  text_left: "A toy of Spiderman, left view"
  text_right: "A toy of Spiderman, right view"
  text_back: "A toy of Spiderman, back view"
  text_overhead: "A toy of Spiderman, overhead view"
  text_bottom: "A toy of Spiderman, bottom view"
  append_direction: True
  shape_path: shapes/Kaws.obj
  z_update_thr: 0.0
optim:
  seed: 3
render:
  alternate_views: False
  views_after: [[0,30],[0,150],
    [45,30],[45,150],
    [90,30],[90,150],
    [135,30],[135,150],
    [180,30],[180,150],
    [225,30],[225,150],
    [270,30],[270,150],
    [315,30],[315,150]
  ]